## 1. Imports

In [4]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Ramya-CF\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Ramya-CF\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Ramya-CF\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

In [3]:
import sys
print(sys.executable)

c:\Users\Ramya-CF\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [6]:
raw_csv = """Name,Age,City,Salary,JoinDate,Gender
Asha,25,Bengaluru,55000,2021-05-12,F
Ravi,30, delhi ,62000,2020-11-03,M
Meena,,Mumbai,58000,2019-07-23,F
Karan,28,BENGALURU,,2022-01-15,M
Asha,25,Bengaluru,55000,2021-05-12,F
Divya,120,Chennai,60000,2020-03-30,F
Suresh,35,Delhi,59000,not_a_date,M
Priya,29,,61000,2021-09-09,F
Anil,40,Mumbai,150000,2018-06-01,M
Zoya,,chennai,57000,2022-02-20,F
"""

with open("sample_raw_data.csv", "w") as f:
    f.write(raw_csv)

df = pd.read_csv("sample_raw_data.csv")
df

     Name    Age       City    Salary    JoinDate Gender
0    Asha   25.0  Bengaluru   55000.0  2021-05-12      F
1    Ravi   30.0     delhi    62000.0  2020-11-03      M
2   Meena    NaN     Mumbai   58000.0  2019-07-23      F
3   Karan   28.0  BENGALURU       NaN  2022-01-15      M
4    Asha   25.0  Bengaluru   55000.0  2021-05-12      F
5   Divya  120.0    Chennai   60000.0  2020-03-30      F
6  Suresh   35.0      Delhi   59000.0  not_a_date      M
7   Priya   29.0        NaN   61000.0  2021-09-09      F
8    Anil   40.0     Mumbai  150000.0  2018-06-01      M
9    Zoya    NaN    chennai   57000.0  2022-02-20      F

## 3. Initial Exploration

In [7]:
df.shape

(10, 6)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      10 non-null     str
 1   Age       8 non-null      float64
 2   City      9 non-null      str
 3   Salary    9 non-null      float64
 4   JoinDate  10 non-null     str
 5   Gender    10 non-null     str
dtypes: float64(2), str(4)
memory usage: 612.0 bytes

In [9]:
df.describe(include='all')

        Name        Age       City         Salary    JoinDate Gender
count     10    8.00000          9       9.000000          10     10
unique     9        NaN          7            NaN           9      2
top     Asha        NaN  Bengaluru            NaN  2021-05-12      F
freq       2        NaN          2            NaN           2      6
mean     NaN   41.50000        NaN   68555.555556         NaN    NaN
std      NaN   32.12031        NaN   30639.480703         NaN    NaN
min      NaN   25.00000        NaN   55000.000000         NaN    NaN
25%      NaN   27.25000        NaN   57000.000000         NaN    NaN
50%      NaN   29.50000        NaN   59000.000000         NaN    NaN
75%      NaN   36.25000        NaN   61000.000000         NaN    NaN
max      NaN  120.00000        NaN  150000.000000         NaN    NaN

In [10]:
# Missing values per column
df.isnull().sum()

Name        0
Age         2
City        1
Salary      1
JoinDate    0
Gender      0
dtype: int64

In [11]:
# Percentage missing per column
(df.isnull().mean() * 100).round(1)

Name         0.0
Age         20.0
City        10.0
Salary      10.0
JoinDate     0.0
Gender       0.0
dtype: float64

## 4. Handle Duplicates

Check for and remove exact duplicate rows (e.g. "Asha" appears twice with identical values).

In [12]:
print("Duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)
df

Duplicate rows: 1

     Name    Age       City    Salary    JoinDate Gender
0    Asha   25.0  Bengaluru   55000.0  2021-05-12      F
1    Ravi   30.0     delhi    62000.0  2020-11-03      M
2   Meena    NaN     Mumbai   58000.0  2019-07-23      F
3   Karan   28.0  BENGALURU       NaN  2022-01-15      M
4   Divya  120.0    Chennai   60000.0  2020-03-30      F
5  Suresh   35.0      Delhi   59000.0  not_a_date      M
6   Priya   29.0        NaN   61000.0  2021-09-09      F
7    Anil   40.0     Mumbai  150000.0  2018-06-01      M
8    Zoya    NaN    chennai   57000.0  2022-02-20      F

## 5. Standardize Text / Categorical Columns

`City` has inconsistent casing and extra whitespace (`" delhi "`, `"BENGALURU"`). Standardize to a consistent title-case format.

In [13]:
df["City"] = df["City"].str.strip().str.title()
df["City"].unique()

<StringArray>
['Bengaluru', 'Delhi', 'Mumbai', 'Chennai', nan]
Length: 5, dtype: str

## 6. Handle Missing Values

- `Age`: numeric → impute with **median** (robust to the outlier age of 120)
- `Salary`: numeric → impute with **mean**
- `City`: categorical → impute with **mode** (most frequent city)
- `JoinDate`: will be fixed after converting to datetime (invalid parses become NaT, then we decide how to handle)

In [14]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["City"] = df["City"].fillna(df["City"].mode()[0])

df.isnull().sum()

Name        0
Age         0
City        0
Salary      0
JoinDate    0
Gender      0
dtype: int64

## 7. Fix Data Types

In [15]:
df["Age"] = df["Age"].astype(int)
df["Salary"] = df["Salary"].astype(float)

# Convert JoinDate; invalid strings like "not_a_date" become NaT
df["JoinDate"] = pd.to_datetime(df["JoinDate"], errors="coerce")

df.dtypes

Name                   str
Age                  int64
City                   str
Salary             float64
JoinDate    datetime64[us]
Gender                 str
dtype: object

In [16]:
# Rows where date failed to parse
df[df["JoinDate"].isnull()]

     Name  Age   City   Salary JoinDate Gender
5  Suresh   35  Delhi  59000.0      NaT      M

In [17]:
# Fill any resulting NaT with the median join date (a reasonable placeholder strategy)
median_date = df["JoinDate"].median()
df["JoinDate"] = df["JoinDate"].fillna(median_date)
df

     Name  Age       City    Salary   JoinDate Gender
0    Asha   25  Bengaluru   55000.0 2021-05-12      F
1    Ravi   30      Delhi   62000.0 2020-11-03      M
2   Meena   30     Mumbai   58000.0 2019-07-23      F
3   Karan   28  Bengaluru   70250.0 2022-01-15      M
4   Divya  120    Chennai   60000.0 2020-03-30      F
5  Suresh   35      Delhi   59000.0 2021-02-06      M
6   Priya   29  Bengaluru   61000.0 2021-09-09      F
7    Anil   40     Mumbai  150000.0 2018-06-01      M
8    Zoya   30    Chennai   57000.0 2022-02-20      F

## 8. Handle Outliers (IQR method)

`Age` has an implausible value (120) and `Salary` has a very high outlier (150000). Use the IQR rule to detect and cap/remove outliers.

In [18]:
def iqr_bounds(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    return Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

age_low, age_high = iqr_bounds(df["Age"])
sal_low, sal_high = iqr_bounds(df["Salary"])

print(f"Age bounds: {age_low:.1f} to {age_high:.1f}")
print(f"Salary bounds: {sal_low:.1f} to {sal_high:.1f}")

Age bounds: 20.0 to 44.0
Salary bounds: 52000.0 to 68000.0

In [19]:
# Flag outliers rather than silently dropping — inspect before deciding
df["Age_outlier"] = ~df["Age"].between(age_low, age_high)
df["Salary_outlier"] = ~df["Salary"].between(sal_low, sal_high)
df[["Name","Age","Age_outlier","Salary","Salary_outlier"]]

     Name  Age  Age_outlier    Salary  Salary_outlier
0    Asha   25        False   55000.0           False
1    Ravi   30        False   62000.0           False
2   Meena   30        False   58000.0           False
3   Karan   28        False   70250.0            True
4   Divya  120         True   60000.0           False
5  Suresh   35        False   59000.0           False
6   Priya   29        False   61000.0           False
7    Anil   40        False  150000.0            True
8    Zoya   30        False   57000.0           False

In [20]:
# Cap outliers to the bound values (winsorizing) instead of dropping rows
df["Age"] = df["Age"].clip(lower=age_low, upper=age_high).astype(int)
df["Salary"] = df["Salary"].clip(lower=sal_low, upper=sal_high)

df = df.drop(columns=["Age_outlier", "Salary_outlier"])
df

     Name  Age       City   Salary   JoinDate Gender
0    Asha   25  Bengaluru  55000.0 2021-05-12      F
1    Ravi   30      Delhi  62000.0 2020-11-03      M
2   Meena   30     Mumbai  58000.0 2019-07-23      F
3   Karan   28  Bengaluru  68000.0 2022-01-15      M
4   Divya   44    Chennai  60000.0 2020-03-30      F
5  Suresh   35      Delhi  59000.0 2021-02-06      M
6   Priya   29  Bengaluru  61000.0 2021-09-09      F
7    Anil   40     Mumbai  68000.0 2018-06-01      M
8    Zoya   30    Chennai  57000.0 2022-02-20      F

## 9. Filtering Examples

In [21]:
# Employees older than 28
df[df["Age"] > 28]

     Name  Age       City   Salary   JoinDate Gender
1    Ravi   30      Delhi  62000.0 2020-11-03      M
2   Meena   30     Mumbai  58000.0 2019-07-23      F
4   Divya   44    Chennai  60000.0 2020-03-30      F
5  Suresh   35      Delhi  59000.0 2021-02-06      M
6   Priya   29  Bengaluru  61000.0 2021-09-09      F
7    Anil   40     Mumbai  68000.0 2018-06-01      M
8    Zoya   30    Chennai  57000.0 2022-02-20      F

In [22]:
# Employees in Bengaluru or Mumbai
df[df["City"].isin(["Bengaluru", "Mumbai"])]

    Name  Age       City   Salary   JoinDate Gender
0   Asha   25  Bengaluru  55000.0 2021-05-12      F
2  Meena   30     Mumbai  58000.0 2019-07-23      F
3  Karan   28  Bengaluru  68000.0 2022-01-15      M
6  Priya   29  Bengaluru  61000.0 2021-09-09      F
7   Anil   40     Mumbai  68000.0 2018-06-01      M

In [23]:
# Female employees earning above the average salary
df[(df["Gender"] == "F") & (df["Salary"] > df["Salary"].mean())]

    Name  Age       City   Salary   JoinDate Gender
6  Priya   29  Bengaluru  61000.0 2021-09-09      F

## 10. GroupBy Examples

In [24]:
# Average salary by city
df.groupby("City")["Salary"].mean().round(2)

City
Bengaluru    61333.33
Chennai      58500.00
Delhi        60500.00
Mumbai       63000.00
Name: Salary, dtype: float64

In [25]:
# Multiple aggregations by gender
df.groupby("Gender").agg(
    avg_age=("Age", "mean"),
    avg_salary=("Salary", "mean"),
    count=("Name", "count")
).round(1)

        avg_age  avg_salary  count
Gender
F          31.6     58200.0      5
M          33.2     64250.0      4

In [26]:
# Add a group-level average back onto every row using transform
df["city_avg_salary"] = df.groupby("City")["Salary"].transform("mean").round(1)
df

     Name  Age       City   Salary   JoinDate Gender  city_avg_salary
0    Asha   25  Bengaluru  55000.0 2021-05-12      F          61333.3
1    Ravi   30      Delhi  62000.0 2020-11-03      M          60500.0
2   Meena   30     Mumbai  58000.0 2019-07-23      F          63000.0
3   Karan   28  Bengaluru  68000.0 2022-01-15      M          61333.3
4   Divya   44    Chennai  60000.0 2020-03-30      F          58500.0
5  Suresh   35      Delhi  59000.0 2021-02-06      M          60500.0
6   Priya   29  Bengaluru  61000.0 2021-09-09      F          61333.3
7    Anil   40     Mumbai  68000.0 2018-06-01      M          63000.0
8    Zoya   30    Chennai  57000.0 2022-02-20      F          58500.0

## 11. Basic Feature Engineering

Create a few derived columns from the cleaned data.

In [27]:
# Extract year/month from JoinDate
df["Join_Year"] = df["JoinDate"].dt.year
df["Join_Month"] = df["JoinDate"].dt.month

# Age group bins
df["Age_Group"] = pd.cut(df["Age"], bins=[0,25,35,60],
                          labels=["Young","Mid-career","Senior"])

# Salary relative to their city's average
df["Salary_vs_City_Avg"] = (df["Salary"] - df["city_avg_salary"]).round(1)

df

,Name,Age,City,Salary,JoinDate,Gender,city_avg_salary,Join_Year,Join_Month,Age_Group,Salary_vs_City_Avg
0,Asha,25,Bengaluru,55000.0,2021-05-12,F,61333.3,2021,5,Young,-6333.3
1,Ravi,30,Delhi,62000.0,2020-11-03,M,60500.0,2020,11,Mid-career,1500.0
2,Meena,30,Mumbai,58000.0,2019-07-23,F,63000.0,2019,7,Mid-career,-5000.0
3,Karan,28,Bengaluru,68000.0,2022-01-15,M,61333.3,2022,1,Mid-career,6666.7
4,Divya,44,Chennai,60000.0,2020-03-30,F,58500.0,2020,3,Senior,1500.0
5,Suresh,35,Delhi,59000.0,2021-02-06,M,60500.0,2021,2,Mid-career,-1500.0
6,Priya,29,Bengaluru,61000.0,2021-09-09,F,61333.3,2021,9,Mid-career,-333.3
7,Anil,40,Mumbai,68000.0,2018-06-01,M,63000.0,2018,6,Senior,5000.0
8,Zoya,30,Chennai,57000.0,2022-02-20,F,58500.0,2022,2,Mid-career,-1500.0

## 12. Final Check & Save Cleaned Data

In [28]:
print("Final shape:", df.shape)
print("\nRemaining missing values:\n", df.isnull().sum())
df.info()

Final shape: (9, 11)

Remaining missing values:
 Name                  0
Age                   0
City                  0
Salary                0
JoinDate              0
Gender                0
city_avg_salary       0
Join_Year             0
Join_Month            0
Age_Group             0
Salary_vs_City_Avg    0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                9 non-null      str
 1   Age                 9 non-null      int64
 2   City                9 non-null      str
 3   Salary              9 non-null      float64
 4   JoinDate            9 non-null      datetime64[us]
 5   Gender              9 non-null      str
 6   city_avg_salary     9 non-null      float64
 7   Join_Year           9 non-null      int32
 8   Join_Month          9 non-null      int32
 9   Age_Group           9 non-null      category
 10  Salary_vs_City_Avg  9 non-null      float64
dtypes: category(1), datetime64[us](1), float64(3), int32(2), int64(1), str(3)
memory usage: 921.0 bytes

In [29]:
df.to_csv("cleaned_data.csv", index=False)
print("Saved cleaned_data.csv")

Saved cleaned_data.csv